name: Semantic Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: 
      - merged

jobs:
  semantic-release:
    if: "!startsWith(github.event.head_commit.message, 'ci')"

    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4.1.1
        id: semantic # Need an `id` for output variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}