name: Semantic Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: 
      - merged

jobs:
  semantic-release:
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !startWith(github.event.head_commit.message, 'ci')"

    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v24.2.3
        id: semantic # Need an `id` for output variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
